apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-chat-deployment
  labels:
    app: rocket-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocket-chat
  template:
    metadata:
      labels:
        app: rocket-chat
    spec:
      containers:
      - name: rocket-chat
        image: rocket.chat:3.18.3
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: rocket-cm   
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rocket-cm
data:
  MONGO_URL: mongodb://mongodb-sc-0.mongodb-sc:27017
  MONGO_OPLOG_URL: mongodb://mongodb-sc-0.mongodb-sc:27017/local?replSet=rs0  


