apiVersion: v1
kind: Service
metadata:
  name: mongodb-v4
  labels:
    app: mongodb-v4
spec:
  ports:
  - port: 80
    targetPort: 27017
    name: mongodb-v4-sts
  type: NodePort
  selector:
    app: mongodb-v4
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-v4
spec:
  serviceName: "mongodb-v4"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb-v4
  template:
    metadata:
      labels:
        app: mongodb-v4
    spec:
      containers:
      - name: mongodb-v4
        image: mongo:4.0.0
        command: 
        - mongod
        - "--bind_ip_all"  
        - "--replSet"
        - rs0
        ports:
        - containerPort: 27017
          name: mongodb-v4-sts
        volumeMounts:
        - name: mongodb-v4-hostpath
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-v4-hostpath
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


