apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-sc
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongodb-sc
  serviceName: mongodb-sc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb-sc
    spec:
      containers:
      - command:
        - mongod
        - --bind_ip_all
        - --replSet
        - rs0
        image: mongo:5.0
        imagePullPolicy: IfNotPresent
        name: rocketmongo
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongo-sc-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: mongo-sc-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 1Gi
